name: Concurency

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  Example:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ github.event }}"
          sleep 30
