name: Context vars

on: push

jobs:
  Example:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -X GET ${{ vars.API_BASE_URL }}
        env:
          MAX_RETRIES: ${{ vars.MAX_RETRIES }}
