name: Context runner

on: push

jobs:
  Example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir ${{ runner.temp }}/out
          touch ${{ runner.temp }}/out/README.md

      - uses: actions/upload-artifact@v3
        with:
          name: Output
          path: ${{ runner.temp }}/out
