name: Context matrix

on: push

jobs:
  Example:
    strategy:
      fail-fast: false
      matrix:
        DOTNET_VERSION: [ '6.x', '7.0' ]
        OS: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.OS }}
    timeout-minutes: 5

    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.DOTNET_VERSION }}
      - run: |
          echo '${{ toJSON(matrix) }}'
