name: Context needs

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}

    steps:
      - name: Build
        id: build_step
        run: echo "build_id=${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Show outputs
        run: echo '${{ toJSON(steps.build_step.outputs) }}'

  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Show outputs
        run: |
          echo Build job ${{ needs.Build.result }}
          echo '${{ toJSON(needs.Build.outputs) }}'

  Success:
    needs: [ Build, Test ]
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - run: echo Success

  Failure:
    needs: [ Build, Test ]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    
    steps:
      - run: echo Failure
