name: Context inputs

on:
  workflow_call:
    inputs:
      username:
        type: string
        required: true
        default: akiojin
    secrets:
      password:
        required: true

jobs:
  Login:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'username=${{ inputs.username }} password=${{ secrets.password }}'
