name: Build and Test
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      run_number: ${{ github.run_number }}
    steps:
      - run: echo Build
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.Build.outputs.run_number }}
  Succeeded:
    needs: [ Build, Test ]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - run: echo Succeeded
  Falied:
    needs: [ Build, Test ]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: echo Failed