name: Reusable workflow (Caller)
on:
  workflow_dispatch:
    inputs:
      USERNAME:
        type: string
        required: true
        default: akiojin
      PASSWORD:
        type: string
        required: true
jobs:
  Build:
    uses: akiojin/GitHubActions/.github/workflows/Workflow007Callee.yml@main
    with:
      username: ${{ inputs.USERNAME }}
    secrets:
      password: ${{ inputs.PASSWORD }}
