on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo github='${{ toJSON(github) }}'
      - run: echo env='${{ toJSON(env) }}'
      - run: echo job='${{ toJSON(job) }}'
      - run: echo steps='${{ toJSON(steps) }}'
      - run: echo runner='${{ toJSON(runner) }}'
      - run: echo secrets='${{ toJSON(secrets) }}'
      - run: echo strategy='${{ toJSON(strategy) }}'
      - run: echo matrix='${{ toJSON(matrix) }}'
      - run: echo needs='${{ toJSON(needs) }}'
      - run: echo inputs='${{ toJSON(inputs) }}'
